### ISSUE TITLE
Librería DDL en visual

### ISSUE THREAD

**Issue by Rosa218** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-Rosa218#2]
[DDL(Reporte).pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-Rosa218/files/6399962/DDL.Reporte.pdf)

**Comment by MariaC232** [comment]
Buen trabajo.
Calificación: 20 puntos

**Comment by josealfredo79** [comment]
El codigo no esta completo no esta bien subido en el repositorio. Favor de checar nuevamente
